### ISSUE TITLE
add phpunit-github-actions-printer to every laravel package

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/API#125]
every package should have this 
```yaml
      - name: require phpunit-github-actions-printer
        run: COMPOSER_ROOT_VERSION=0.9.9 composer require --dev mheap/phpunit-github-actions-printer

      - name: Run tests
        run: XDEBUG_MODE=coverage vendor/bin/phpunit  --coverage-clover coverage.xml --printer mheap\\GithubActionsReporter\\Printer
```
